import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>SEE REAL ESTATE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/images/LogoMakr.png" />
      </Head>

    </div>
  )
}
